base_url = "https://www.pkmnapi.com"
build_search_index = true
compile_sass = true
highlight_code = true
theme = "book"
title = "pkmnapi"
hard_link_static = true

[extra]
api_domain = "https://api.pkmnapi.com"
