[package]
name = "pkmnapi-db"
version = "0.1.0"
authors = ["Kevin Selwyn <kevinselwyn@gmail.com>"]
edition = "2018"

[features]
default = []
PKMN_RED = []
PKMN_BLUE = []

[dependencies]
byteorder = "1.3.4"
hound = "3.4.0"
image = "0.23.7"
md5 = "0.7.0"
