name: Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: site
        TOKEN: ${{ secrets.TOKEN }}
